// --- 50 PRACTICAL LEGAL TIPS (Strings) ---
export const LEGAL_TIPS = [
  "Treat every email as a legal document; what you type can be used in court.",
  "Never sign a contract with empty spaces; draw a line through them.",
  "In India, a Digital Signature is as binding as a physical one.",
  "Take photos of a rental property *before* moving in to protect your deposit.",
  "A 'Nominee' is a caretaker, not the ultimate owner of the property.",
  "Always check the 'Lock-in Period' in a lease before signing.",
  "Registered Post with 'Acknowledgement Due' is best for legal notices.",
  "Section 138: A bounced cheque is a criminal offense in India.",
  "Privacy Tip: If a free app asks for Gallery access, YOU are the product.",
  "The Consumer Protection Act (2019) now covers E-commerce shopping.",
  "Police are technically always 'on duty' even without a uniform.",
  "Employers cannot fire a woman just for being pregnant (Maternity Act).",
  "LPG Insurance: Gas explosions can be claimed for up to ₹40 Lakhs.",
  "Zero FIR: File a report at ANY police station, regardless of location.",
  "Free Legal Aid: NALSA provides free lawyers if you can't afford one.",
  "Right to Silence: You don't have to speak if it self-incriminates you.",
  "Daughters have equal rights to ancestral property as sons since 2005.",
  "You can't be detained for 24+ hours without seeing a magistrate.",
  "DPDP Act 2023: You can request any company to delete your data.",
  "RTI Act: Citizens can request info from public authorities (30-day limit).",
  "Service Charge in restaurants is voluntary, not mandatory.",
  "Women cannot be arrested after sunset without a Magistrate order.",
  "Traffic Police must provide a valid receipt for any fine collected.",
  "Shops cannot legally sell products above the printed MRP.",
  "Hospitals cannot refuse road accident victims for lack of money.",
  "IT Act 66A was struck down; online criticism is protected speech.",
  "Never sign an empty affidavit; it's a sworn statement under penalty.",
  "Landlords must give reasonable notice (usually 30 days) before eviction.",
  "An unstamped agreement is often not valid in court; pay your duty.",
  "POSH Act: 10+ employees require a sexual harassment committee.",
  "Employing children under 14 is a punishable crime in India.",
  "Your code is copyrighted the moment you create it, even without a logo.",
  "Registering a Will makes it significantly harder to challenge later.",
  "Arbitration clauses help settle disputes faster than regular courts.",
  "Register your brand trademark early to prevent business identity theft.",
  "General PoA is risky; use 'Special' PoA for specific tasks only.",
  "Report unhygienic food or adulteration to FSSAI online instantly.",
  "Article 21: You have the right to a reasonably speedy trial.",
  "Police cannot handcuff an accused unless there is a high escape risk.",
  "Drunk Driving: Refusing a breathalyzer test is a legal violation.",
  "Both rider and pillion must wear ISI-certified helmets in India.",
  "Report cyber bullying or online harassment at cybercrime.gov.in.",
  "RTE Act: Kids aged 6-14 have a right to free compulsory education.",
  "Paying less than the 'Minimum Wage' is a punishable labor offense.",
  "Filing ITR with zero income still helps with future loans and visas.",
  "Lok Adalats are great for quick, free out-of-court settlements.",
  "Property gift deeds must be registered and stamped to be legal.",
  "Ancestral property belongs to the whole lineage, not just one person.",
  "5+ years of work in one company entitles you to Gratuity pay.",
  "Always check RERA registration before buying a new flat or plot."
];

// --- 50 UNIQUE & FUNNY CASE STUDIES (Strings) ---
export const CASE_STUDIES = [
  "Ahmedabad: A man sued a hotel for mosquito bites and won ₹10,000.",
  "Emoji Law: A Canadian judge ruled a 'Thumbs Up' emoji is a signature.",
  "The Papad War: Indian courts ruled Papads are NOT taxable biscuits.",
  "Red Bull: Paid $13M because the drink didn't actually 'give you wings.'",
  "The Haunted House: A NY court ruled a seller must disclose ghosts.",
  "Delhi: A woman won ₹2 Crores after a salon gave her a bad haircut.",
  "Subway: Sued because 'Footlong' subs were only 11 inches long.",
  "The 22-Year Case: A man sued railways for 22 years over a ₹20 overcharge.",
  "Pringles: The brand sued itself to prove they aren't potato chips.",
  "Pepsi Jet: A man sued for a Harrier Jet promised in a joke ad.",
  "Starbucks: Sued because iced coffee allegedly had 'too much ice.'",
  "Beer Ad Suit: A man sued because ads didn't lead to meeting beautiful women.",
  "Sued Parents: A man sued his parents for giving birth without consent.",
  "Sued the Weather: A woman sued a TV station for a wrong rain forecast.",
  "Movie Spoiler Suit: A man sued a friend for spoiling a film ending.",
  "Hairy Hand: A chest-skin graft made hair grow on a man's palm.",
  "The 1-Minute Call: A client sued a lawyer for a full hour's fee for 1 min.",
  "Dry Biryani: A restaurant was fined for serving biryani without gravy.",
  "Quiet Library: A man sued a library for being 'too quiet' and lonely.",
  "Fruit Loops: Sued because the 'fruit' in the name isn't real fruit.",
  "Taco Bell: Sued because beef was allegedly only 35% actual meat.",
  "Boneless Bone: A man sued after finding a bone in a 'boneless' wing.",
  "No Makeup Suit: A man sued his wife after seeing her natural face.",
  "Twin Reputation: A man sued his twin for being rude and ruining his image.",
  "NASA Gravity: A man sued NASA for 'disturbing his orbital balance.'",
  "Missing Pickle: A man sued a burger chain for forgetting his pickle.",
  "5-Minute Delay: A passenger sued an airline for a tiny flight delay.",
  "Fake Psychic: A man sued because a predicted future didn't happen.",
  "Too Qualified: A man sued for not being hired due to 'over-qualification.'",
  "Mosquito Coil: A man sued because a '12-hour' coil lasted only 10 hours.",
  "Broken Engagement: A woman was awarded $50k after a 10-year breakup.",
  "SeaWorld: Sued after a boy hid in the park and was killed by an Orca.",
  "College Suit: A grad sued her college because she couldn't find a job.",
  "Toddler Trip: A woman sued a store after tripping over her own child.",
  "Student Art: A billionaire sued after buying a student's 'masterpiece.'",
  "Ghosting Suit: A man sued a woman for $10k after she ghosted a date.",
  "Green Wrist: A man sued a brand because his 'gold' watch turned green.",
  "Snoring Suit: A woman sued her husband for extreme snoring.",
  "Candy Syrup: Brand sued for claiming 'Real Fruit' on corn syrup candy.",
  "The Pants Suit: A judge sued a dry cleaner for $54M over lost trousers.",
  "Twinkie Defense: A killer argued junk food caused mental instability.",
  "Sleepwalking Killer: A man was acquitted after proving he was sleepwalking.",
  "Stiff Shoes: A man blamed speeding on his 'stiff new shoes.'",
  "Dumpster Spot: Woman argued she parked illegally because a bin took her spot.",
  "Bedazzled Ankle: A judge told a dancer to bedazzle her ankle monitor.",
  "Landscaper CEO: A CEO dressed as a gardener to avoid alimony.",
  "Bad Luck Insurance: A man sued his insurer for not covering his 'bad luck.'",
  "Free Mansion: A man used ancient squatter laws to live in a $16M home.",
  "Rooster Noise: A man sued a neighbor because a rooster crowed at 4 AM.",
  "15-Minute Lawyer: Client sued a lawyer who billed for a 1-sentence email."
];